name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
      - name: Setup node
        run: npm install
      - name: Authorship
        run: git config --global user.email "annabellestrong@gmail.com"
      - name: Build React app
        run: npm run build
      - name: Update gh-pages branch
        run: npm run deploy
