name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
      - run: npm run build
      - run: npm run deploy
